### ISSUE TITLE
Velocity cli error

### ISSUE THREAD

**Issue by AntonShevel** [shepherdwind/velocity.js#109]
When I try to execute the following command
```
velocity --build api/appsync/mapping-templates/item/createItem.request.json.vm
```
I get the following error
```
read file api/appsync/mapping-templates/item/createItem.request.json.vm
.../node_modules/velocityjs/bin/velocity-cli.js:38
      var asts = Parser._parse(str);
                        ^

TypeError: Cannot read property '_parse' of undefined
    at /Users/zerg/Work/fr/moja-backend/node_modules/velocityjs/bin/velocity-cli.js:38:25
    at Array.forEach (<anonymous>)
    at Object.buildAst (/Users/zerg/Work/fr/moja-backend/node_modules/velocityjs/bin/velocity-cli.js:30:9)
    at Object.<anonymous> (/Users/zerg/Work/fr/moja-backend/node_modules/velocityjs/bin/velocity:15:11)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
```

velocityjs version is 1.1.1
node v8.9.3

**Comment by shepherdwind** [comment]
New version 1.1.2 published. You can try it now.

**Comment by AntonShevel** [comment]
thanks @shepherdwind !
