### ISSUE TITLE
变量名称是null时报错

### ISSUE THREAD

**Issue by king-king** [shepherdwind/velocity.js#139]
**源码**
```
##空值替换
#set($null = "<span style='color: #B2B2B2'>-</span>")
```
**报错**
```bash
Error: Parse error on line 2:
##空值替换#set($null = "<span style=
------------^
Expecting 'ID', 'MAP_BEGIN', 'VAR_BEGIN', got 'BOOL'
    at Parser.parseError (D:\TEMP\temp\node_modules\?[4mvelocityjs?[24m\src\parse\index.js:322:21)
    at Parser.parse (D:\TEMP\temp\node_modules\?[4mvelocityjs?[24m\src\parse\index.js:389:22)
    at exports.parse (D:\TEMP\temp\node_modules\?[4mvelocityjs?[24m\src\parse\index.js:1012:53)
    at parse (D:\TEMP\temp\node_modules\?[4mvelocityjs?[24m\src\parse.js:24:14)
    at Object.Velocity.render (D:\TEMP\temp\node_modules\?[4mvelocityjs?[24m\src\velocity.js:16:14)
    at Object.<anonymous> (D:\TEMP\temp\script\render.js:4:43)
?[90m    at Module._compile (internal/modules/cjs/loader.js:1147:30)?[39m
?[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)?[39m
?[90m    at Module.load (internal/modules/cjs/loader.js:996:32)?[39m
?[90m    at Function.Module._load (internal/modules/cjs/loader.js:896:14)?[39m {
  hash: {
    text: ?[32m'null'?[39m,
    token: ?[32m'BOOL'?[39m,
    line: ?[33m1?[39m,
    loc: { first_line: ?[33m2?[39m, last_line: ?[33m2?[39m, first_column: ?[33m5?[39m, last_column: ?[33m6?[39m },
    expected: [ ?[32m"'ID'"?[39m, ?[32m"'MAP_BEGIN'"?[39m, ?[32m"'VAR_BEGIN'"?[39m ]
  }
}

```

**Comment by shepherdwind** [comment]
额，null 被识别成了 boolean 值了
