### ISSUE TITLE
#set with array fails for unknown reason

### ISSUE THREAD

**Issue by vortex314** [shepherdwind/velocity.js#153]
Thanks for this great work on implementing velocity in Javascript. It works fine, but I have a case where I fail to understand where I did somethig wrog.
This code snippet 
```
    <body>
    <h1><u>INGBNL2S</u></h1>
    #set( $directions = ["EMS","RCP"] ) 
    #foreach ( $direction in $directions )
    <h2>$direction</h2>
        <table >
```
generates this issue
```
/Users/mg61dd/workspace/velocity/node_modules/velocityjs/src/parse.js:83
      _ret.arr.unshift(block[i]);
               ^

TypeError: Cannot read properties of undefined (reading 'unshift')
    at makeLevel (/Users/mg61dd/workspace/velocity/node_modules/velocityjs/src/parse.js:83:16)
    at parse (/Users/mg61dd/workspace/velocity/node_modules/velocityjs/src/parse.js:41:13)
    at Object.Velocity.render (/Users/mg61dd/workspace/velocity/node_modules/velocityjs/src/velocity.js:16:14)
    at Server.<anonymous> (/Users/mg61dd/workspace/velocity/app.js:25:20)
    at Server.emit (node:events:526:28)
    at parserOnIncoming (node:_http_server:951:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
```

**Comment by vortex314** [comment]
Sorry mistake. I was missing a closing 'end' .
