### ISSUE TITLE
数值解析错误

### ISSUE THREAD

**Issue by popomore** [shepherdwind/velocity.js#21]
```
#set($ratio=$height*1.0/$width*1.0)
```

错误

```
Error: Lexical error on line 2. Unrecognized text.
...set($ratio=$height*1.0/$width*1.0)<div 
-----------------------^
    at Object.parseError (/Users/popomore/nvm/v0.8.10/lib/node_modules/velocityjs/src/parse/index.js:267:11)
    at Object.parseError (/Users/popomore/nvm/v0.8.10/lib/node_modules/velocityjs/src/parse/index.js:378:28)
    at Object.lexer.next (/Users/popomore/nvm/v0.8.10/lib/node_modules/velocityjs/src/parse/index.js:514:25)
    at Object.lex (/Users/popomore/nvm/v0.8.10/lib/node_modules/velocityjs/src/parse/index.js:519:22)
    at lex (/Users/popomore/nvm/v0.8.10/lib/node_modules/velocityjs/src/parse/index.js:289:28)
    at Object.parse (/Users/popomore/nvm/v0.8.10/lib/node_modules/velocityjs/src/parse/index.js:302:26)
    at Object.exports.parse (/Users/popomore/nvm/v0.8.10/lib/node_modules/velocityjs/src/parse/index.js:736:53)
    at getVTL (/Users/popomore/nvm/v0.8.10/lib/node_modules/velocityjs/bin/velocity-cli.js:139:21)
    at Object.jsonify (/Users/popomore/nvm/v0.8.10/lib/node_modules/velocityjs/bin/velocity-cli.js:130:17)
    at Object.<anonymous> (/Users/popomore/nvm/v0.8.10/lib/node_modules/velocityjs/bin/velocity:23:11)
```

**Comment by muzi131313** [comment]
@shepherdwind 现在支持小数格式化么？比如说：
15.52我想格式化成15.5这样的数值；
在网上找到的其他人的实现
`#macro(oneNum $num)
    #set($string = $num+"") 
    #set($stringList = $stringUtil.split($string,"."))  
    #set($strSize = $stringList.size())  
    #if($strSize==2) 
        #set($subStr = $stringList.get(1))  
        #set($subStrSize = $subStr.length())  
        #if($subStrSize>1)  
            $stringList.get(0).$subStr.substring(0,1)  
        #else  
            $stringList.get(0).$subStr  
        #end
    #else
        $string  
    #end
#end`，
还有一种是`number.format('#0.0', 12.35)`，
这两种都需要后台配置，有没有velocity原生支持格式化小数位的？
后台不知道怎么配置。ps: [数值、日期格式化](http://blog.csdn.net/gaojinshan/article/details/38850721)、[stackoverlfow: format number in velocity template](http://stackoverflow.com/questions/8820240/how-to-format-numbers-in-velocity-templates)

**Comment by shepherdwind** [comment]
@muzi131313 这种问题可以单独提一个 issue 的。

原生的 velocity 是 java ，在 js 中可以拿到 js 数字对象，你可以 $number.toFixed(2) 应该就可以了

**Comment by muzi131313** [comment]
@shepherdwind 大神就是大神，一下子就解决了我纠结N久的问题。一直纠结velocity需要后台支持，忘记咱们这个版本是支持js语法的
